services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: CRUD-Service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./server/static:/app/static